### ISSUE TITLE
In BS 1.6.1, everything is displaced to the left when ME is active

### ISSUE THREAD

**Issue by Arakon** [Kylemc1413/QuestMods#13]
This is presumably due to the new "room rotation" setting added in 1.6.1.

**Comment by DragonFlightStudios** [comment]
I wrote a little workaround for this. Surely it is not going to replace a fix of ME but it makes the songs playable again without changing your room offset by a lot to the right.
However, you still want to move the floor up a bit because for some reason my changes do not affect the height. 
Anyways, to use it:
* unzip it and open the BeatSaberOffsetter.html in a browser with JavaScript enabled (no internet connection used/required)
* It will allow you to offset the displaced blocks so they should be fine again.
* Entered values worked for most songs for me but not all.
* Further instructions on the html

Download here:
[BeatSaberOffsetter.zip](https://github.com/Kylemc1413/QuestMods/files/4051132/BeatSaberOffsetter.zip)

**Comment by Kylemc1413** [comment]
That behavior is occuring because you're using a version of mapping extensions not meant for that version of the game.
